apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-se-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /se
spec:
  rules:
  - host: example.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-se-service
            port:
              name: http
